Added fn from_ansi_str for StyledObject
console-rs/console pull request #167
Opened 2023-05-18 09:04 UTC by BppleMan

this is method can parse a string with ansi escape code and return a vector of StyledObject

2023-05-18 10:42 UTC, mitsuhiko commented
This looks good but I think it would be better to change this to return an Iterator instead. Also please add an example docstring showing this is to be used, maybe just use the example from #166.

2023-05-19 08:53 UTC, BppleMan commented
Refactor parser into iterator, and provide it together with AnsiCodeIterator following ansi_parse feature, optimize unit test

2023-05-19 08:57 UTC, BppleMan commented
Any suggestions on where to add more documentation?

2023-05-19 10:19 UTC, closed without merging

2023-05-22 02:39 UTC, BppleMan commented
@mitsuhiko can you review this pr

2024-01-09 15:39 UTC, mitsuhiko requested changes

2024-01-09 15:39 UTC, mitsuhiko commented on Cargo.toml
> +regex = "1.4.2"
This should be an optional dependency. Code that depends on it then should also be feature gated.

2024-01-09 15:39 UTC, mitsuhiko commented on src/utils.rs
> +    pub fn get_fg(&self) -> Option<Color> {
Why are these APIs added? Let's not add these unless there is a reason (maybe follow up PR), and if they are added, they need docs.